AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for RecipeGo website a devops project

Globals:
  Function:
    Timeout: 10
    Runtime: provided.al2023
    MemorySize: 128
    Environment:
      Variables:
        MAIN_TABLE: !Ref MainTable

Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: nickname
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # to allow us to query by nickname if need be
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: nickname
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RecipeUserPool
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: nickname
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: recipe-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  # api gateway
  RecipeApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - DELETE
          - PUT
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
              audience:
                - !Ref CognitoUserPoolClient

  # to add newly created user to dynamo db
  AddUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/add_user/add_user.zip
      Handler: bootstrap
      Architectures: [arm64]
      Description: Lambda function that runs after user successfully signs up to add them to dynamodb
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:AdminGetUser
              - cognito-idp:AdminDeleteUser
            Resource: "*"
      Events:
        CognitoTrigger:
          Type: Cognito
          Properties:
            UserPool: !Ref CognitoUserPool
            Trigger: PostConfirmation
